networks:
  estia_menage_network:
    external: true
    name: estia-menage-api_estia_menage_api_network

services:
  estia-menage-ui-web:
    container_name: estia-menage-ui-web
    build:
      context: .
      target: development
    ports:
      - "19020:19000"   # Metro Bundler manifest
      - "19021:19001"   # WebSocket debugging
      - "19022:19002"   # Manifest
      - "19023:19003"   # Tunnel
      - "19026:19006"   # Expo DevTools
      - "18083:8083"    # Metro Bundler
    environment:
      REACT_NATIVE_PACKAGER_HOSTNAME: ${REACT_NATIVE_PACKAGER_HOSTNAME:-192.168.1.228}
      EXPO_PACKAGER_PROXY_URL: ${EXPO_PACKAGER_PROXY_URL:-}
      EXPO_DEVTOOLS_LISTEN_ADDRESS: ${EXPO_DEVTOOLS_LISTEN_ADDRESS:-0.0.0.0}
      EXPO_PUBLIC_API_URL: ${EXPO_PUBLIC_API_URL:-http://192.168.1.228:3010}
      EXPO_PUBLIC_API_KEY: ${EXPO_PUBLIC_API_KEY:-local-dev-api-key}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    networks:
      - estia_menage_network
